### ISSUE TITLE
codegenx64 type expected error

### ISSUE THREAD

**Issue by ment1na** [RSDuck/hocuspocube#2]
```
hocuspocube-master/hocuspocube/util/jit/codegenx64.nim(151, 19) Error: type expected, but got: 
when T is HostIRegRange:
  Register64
 else: RegisterXmm
```

**Comment by RSDuck** [comment]
what Nim version are you using? I think there was a compiler bug where `when` expressions where broken at some point, but it got fixed.

**Comment by ment1na** [comment]
> what Nim version are you using? I think there was a compiler bug where `when` expressions where broken at some point, but it got fixed.

1.6.0, i'll try to update and retry

**Comment by ment1na** [comment]
looks like even updating does not fix it

**Comment by RSDuck** [comment]
ok I just double checked the code indeed doesn't work even with Nim 1.6.6, it does work though with Nim build from latest devel source (which is what I'm using). I'm going to implement a workaround nonetheless.
