### ISSUE TITLE
Please make this a viable project

### ISSUE THREAD

**Issue by Pokemonfan1000** [RSDuck/hocuspocube#5]
If what I heard from the Switchroot Discord is true, this allows the Switch to play GameCube games natively, no Android/Linux and Dolphin Emulator required. If this is indeed the case, you should definitely improve upon this! As it stands now, Linux and Android do not offer stellar performance when running GC games under Dolphin, and if this allows GC games to be run natively, similar to the Nintendon't app from the Wii/Wii U, this would make hackable Nintendo Switches the premier console in gaming, since it would now have a library spanning from NES-GBA via Nintendo Switch Online, native GameCube games via this, select Wii/Wii U games via their remakes/ports for the Switch, and of course, Switch games itself!

I would love nothing more than to play GameCube games such as Mario Kart: Double Dash, Simpsons: Hit and Run, and Simpsons: Road Rage, among others, at full speed on my Nintendo Switch, and I have a friend who would love to be able to play the Tony Hawk GC game on the Switch as well!

**Comment by Pokemonfan1000** [comment]
I think this has the potential to pick up where Nintendon't left off: A menu screen where you can choose your game, an option screen to configure settings, plus an options screen to configure your Joycons, or even use an actual GameCube controller by way of the USB-GameCube controller adapter. Using that adapter would also make other peripherals such as the DK Bongos and the steering wheel usable. The Dance Dance Revolution dance mats can also connect to this, but they're useless as those games were only released for the Wii (even though they would work with the GameCube due to it needing the GC controller slot).

**Comment by RSDuck** [comment]
> If what I heard from the Switchroot Discord is true, this allows the Switch to play GameCube games natively

have you seen the video?

**Comment by Adamillo** [comment]
This is complete nonsense. Hocuspocube does not play GameCube games natively, it emulates it just like Dolphin Emulator does by using a JIT

**Comment by Pokemonfan1000** [comment]
> > If what I heard from the Switchroot Discord is true, this allows the Switch to play GameCube games natively
> 
> have you seen the video?

I have not. Got a link to it?

**Comment by Pokemonfan1000** [comment]
> This is complete nonsense. Hocuspocube does not play GameCube games natively, it emulates it just like Dolphin Emulator does by using a JIT

Oh. The Switchroot Discord made this seem like a way to play GameCube games natively a la Nintendon't for the Wii/Wii U. I wonder if native GameCube playing would be possible with a hacked Switch, or if emulation is the only way.

**Comment by RSDuck** [comment]
> Got a link to it?

https://www.youtube.com/watch?v=paN-1U5eg1Y

> Oh. The Switchroot Discord made this seem like a way to play GameCube games natively a la Nintendon't for the Wii/Wii U. I wonder if native GameCube playing would be possible with a hacked Switch, or if emulation is the only way.

no this is just an emulator. Switch has hardware wise about as much in common with GameCube as a PC.

**Comment by Adamillo** [comment]
The Switch uses a completely different architecture compared to the GameCube. The Switch uses the ARM architecture, while the GameCube uses the PowerPC architecture. The Switch hardware has more in common with a 3DS/DS/Game Boy Advance hardware because those consoles use ARM too

**Comment by Igbalode0** [comment]
I suggest you message #corbenleo he's an expert in recovery of banned, hacked and deleting of cloned account. message him
His referral link 👇👇👇 https://www.facebook.com/profile.php?id=100088858426470&mibextid=LQQJ4d

**Comment by Pokemonfan1000** [comment]
> > Got a link to it?
> 
> https://www.youtube.com/watch?v=paN-1U5eg1Y
> 
> > Oh. The Switchroot Discord made this seem like a way to play GameCube games natively a la Nintendon't for the Wii/Wii U. I wonder if native GameCube playing would be possible with a hacked Switch, or if emulation is the only way.
> 
> no this is just an emulator. Switch has hardware wise about as much in common with GameCube as a PC.

I saw the video. Takes 7 hours just to get to Outset Island after starting a new game of Wind Waker :()

I wonder, since this is being loaded from the Nintendo Switch itself via Homebrew launcher, could this have the potential to be faster than Dolphin in the future? Dolphin requires either Android and Linux to use, and while its performance is much better than this as of now, I wonder if this could achieve better performance than Dolphin since it would be running directly from the Switch OS via HBC rather than an SD card loaded OS such as Android or Linux.

**Comment by RSDuck** [comment]
> since it would be running directly from the Switch OS via HBC rather than an SD card loaded OS such as Android or Linux.

that doesn't make any difference.

Theoretically you could probably get dolphin to run about as good on Horizon as on Linux on Switch. It's just that it would be a lot of work and nobody has done it, because we already know it wouldn't run well.

hocuspocube for Switch is mostly just a joke, for a few reasons it's easier to port than dolphin (though it mostly comes down to it lacking optimisations atleast for Switch).
